# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignDT1.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 623)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setWindowOpacity(2.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_welcome = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_welcome.sizePolicy().hasHeightForWidth())
        self.label_welcome.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(19, 92, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 92, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_welcome.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_welcome.setFont(font)
        self.label_welcome.setObjectName("label_welcome")
        self.horizontalLayout_4.addWidget(self.label_welcome)
        spacerItem = QtWidgets.QSpacerItem(149, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tum_logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tum_logo.sizePolicy().hasHeightForWidth())
        self.tum_logo.setSizePolicy(sizePolicy)
        self.tum_logo.setMinimumSize(QtCore.QSize(150, 60))
        self.tum_logo.setMaximumSize(QtCore.QSize(150, 60))
        self.tum_logo.setText("")
        self.tum_logo.setPixmap(QtGui.QPixmap("logo_tum.png"))
        self.tum_logo.setScaledContents(True)
        self.tum_logo.setObjectName("tum_logo")
        self.horizontalLayout_7.addWidget(self.tum_logo)
        self.wfp_logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wfp_logo.sizePolicy().hasHeightForWidth())
        self.wfp_logo.setSizePolicy(sizePolicy)
        self.wfp_logo.setMinimumSize(QtCore.QSize(90, 90))
        self.wfp_logo.setMaximumSize(QtCore.QSize(90, 90))
        self.wfp_logo.setText("")
        self.wfp_logo.setPixmap(QtGui.QPixmap("logo_wfp.png"))
        self.wfp_logo.setScaledContents(True)
        self.wfp_logo.setObjectName("wfp_logo")
        self.horizontalLayout_7.addWidget(self.wfp_logo)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, 10, 10, 30)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.text_top = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_top.setFont(font)
        self.text_top.setObjectName("text_top")
        self.horizontalLayout_6.addWidget(self.text_top)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_selectfiles = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_selectfiles.setFont(font)
        self.groupBox_selectfiles.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_selectfiles.setAutoFillBackground(False)
        self.groupBox_selectfiles.setStyleSheet("")
        self.groupBox_selectfiles.setFlat(False)
        self.groupBox_selectfiles.setObjectName("groupBox_selectfiles")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_selectfiles)
        self.gridLayout_2.setContentsMargins(-1, -1, 9, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.browseButton_capac = QtWidgets.QPushButton(self.groupBox_selectfiles)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.browseButton_capac.setFont(font)
        self.browseButton_capac.setObjectName("browseButton_capac")
        self.gridLayout.addWidget(self.browseButton_capac, 1, 2, 1, 1)
        self.lineEdit_gps = QtWidgets.QLineEdit(self.groupBox_selectfiles)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_gps.setFont(font)
        self.lineEdit_gps.setObjectName("lineEdit_gps")
        self.gridLayout.addWidget(self.lineEdit_gps, 0, 1, 1, 1)
        self.browseButton_cons = QtWidgets.QPushButton(self.groupBox_selectfiles)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.browseButton_cons.setFont(font)
        self.browseButton_cons.setObjectName("browseButton_cons")
        self.gridLayout.addWidget(self.browseButton_cons, 2, 2, 1, 1)
        self.label_choose_cons = QtWidgets.QLabel(self.groupBox_selectfiles)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_cons.setFont(font)
        self.label_choose_cons.setObjectName("label_choose_cons")
        self.gridLayout.addWidget(self.label_choose_cons, 2, 0, 1, 1)
        self.lineEdit_cons = QtWidgets.QLineEdit(self.groupBox_selectfiles)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_cons.setFont(font)
        self.lineEdit_cons.setObjectName("lineEdit_cons")
        self.gridLayout.addWidget(self.lineEdit_cons, 2, 1, 1, 1)
        self.label_choose_capac = QtWidgets.QLabel(self.groupBox_selectfiles)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_capac.setFont(font)
        self.label_choose_capac.setObjectName("label_choose_capac")
        self.gridLayout.addWidget(self.label_choose_capac, 1, 0, 1, 1)
        self.label_choose_gps = QtWidgets.QLabel(self.groupBox_selectfiles)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_gps.setFont(font)
        self.label_choose_gps.setTextFormat(QtCore.Qt.AutoText)
        self.label_choose_gps.setObjectName("label_choose_gps")
        self.gridLayout.addWidget(self.label_choose_gps, 0, 0, 1, 1)
        self.lineEdit_capac = QtWidgets.QLineEdit(self.groupBox_selectfiles)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_capac.setFont(font)
        self.lineEdit_capac.setObjectName("lineEdit_capac")
        self.gridLayout.addWidget(self.lineEdit_capac, 1, 1, 1, 1)
        self.browseButton_gps = QtWidgets.QPushButton(self.groupBox_selectfiles)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.browseButton_gps.setFont(font)
        self.browseButton_gps.setObjectName("browseButton_gps")
        self.gridLayout.addWidget(self.browseButton_gps, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_selectfiles)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_details = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_details.sizePolicy().hasHeightForWidth())
        self.groupBox_details.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_details.setFont(font)
        self.groupBox_details.setObjectName("groupBox_details")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_details)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spinBox_TimeHorizon = QtWidgets.QSpinBox(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_TimeHorizon.sizePolicy().hasHeightForWidth())
        self.spinBox_TimeHorizon.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_TimeHorizon.setFont(font)
        self.spinBox_TimeHorizon.setWrapping(False)
        self.spinBox_TimeHorizon.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_TimeHorizon.setAccelerated(True)
        self.spinBox_TimeHorizon.setMinimum(1)
        self.spinBox_TimeHorizon.setMaximum(12)
        self.spinBox_TimeHorizon.setObjectName("spinBox_TimeHorizon")
        self.gridLayout_3.addWidget(self.spinBox_TimeHorizon, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.label_choose_time = QtWidgets.QLabel(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_choose_time.sizePolicy().hasHeightForWidth())
        self.label_choose_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_time.setFont(font)
        self.label_choose_time.setObjectName("label_choose_time")
        self.gridLayout_3.addWidget(self.label_choose_time, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_details)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 0, 1, 1)
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        self.pushButton_close.setMinimumSize(QtCore.QSize(170, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_5.addWidget(self.pushButton_close, 1, 2, 1, 1)
        self.pushButton_opt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_opt.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_opt.sizePolicy().hasHeightForWidth())
        self.pushButton_opt.setSizePolicy(sizePolicy)
        self.pushButton_opt.setMinimumSize(QtCore.QSize(170, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_opt.setFont(font)
        self.pushButton_opt.setCheckable(False)
        self.pushButton_opt.setObjectName("pushButton_opt")
        self.gridLayout_5.addWidget(self.pushButton_opt, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 22))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDecision_Tool_Help = QtWidgets.QAction(MainWindow)
        self.actionDecision_Tool_Help.setObjectName("actionDecision_Tool_Help")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Cliparts/clipart schließen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.menuHelp.addAction(self.actionDecision_Tool_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label_choose_cons.setBuddy(self.lineEdit_cons)
        self.label_choose_capac.setBuddy(self.lineEdit_capac)
        self.label_choose_gps.setBuddy(self.lineEdit_gps)
        self.label_choose_time.setBuddy(self.spinBox_TimeHorizon)

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.pushButton_close.pressed.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_gps, self.browseButton_gps)
        MainWindow.setTabOrder(self.browseButton_gps, self.lineEdit_capac)
        MainWindow.setTabOrder(self.lineEdit_capac, self.browseButton_capac)
        MainWindow.setTabOrder(self.browseButton_capac, self.lineEdit_cons)
        MainWindow.setTabOrder(self.lineEdit_cons, self.browseButton_cons)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Decision Tool WFP@TUM"))
        self.label_welcome.setText(_translate("MainWindow", "Welcome to the Optimization Decision Tool!"))
        self.text_top.setText(_translate("MainWindow", "Select the appropriate files below, define your time horizon and click on \'Optimize\' to get your optimal route.  It will also\n"
"give you all information about the assignments as an output."))
        self.groupBox_selectfiles.setTitle(_translate("MainWindow", "Select files"))
        self.browseButton_capac.setStatusTip(_translate("MainWindow", "Select the file with the capacities of schools, warehouses and trucks."))
        self.browseButton_capac.setText(_translate("MainWindow", "Browse"))
        self.browseButton_cons.setStatusTip(_translate("MainWindow", "Select the file with the consumptions per day of each school."))
        self.browseButton_cons.setText(_translate("MainWindow", "Browse"))
        self.label_choose_cons.setText(_translate("MainWindow", "Choose file with consumptions per day:"))
        self.label_choose_capac.setText(_translate("MainWindow", "Choose file with capacities:"))
        self.label_choose_gps.setText(_translate("MainWindow", "Choose main file:"))
        self.browseButton_gps.setStatusTip(_translate("MainWindow", "Select the file with all data for warehouses and schools."))
        self.browseButton_gps.setText(_translate("MainWindow", "Browse"))
        self.groupBox_details.setTitle(_translate("MainWindow", "More details"))
        self.spinBox_TimeHorizon.setStatusTip(_translate("MainWindow", "Choose the number of weeks over which it will optimize."))
        self.label_choose_time.setText(_translate("MainWindow", "Time Horizon:"))
        self.pushButton_close.setStatusTip(_translate("MainWindow", "Click here to exit the decision tool."))
        self.pushButton_close.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_close.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_opt.setStatusTip(_translate("MainWindow", "Click here to start the optimization."))
        self.pushButton_opt.setText(_translate("MainWindow", "Optimize"))
        self.pushButton_opt.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About the developers"))
        self.actionDecision_Tool_Help.setText(_translate("MainWindow", "Decision Tool - Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
