# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignDT_testing2.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 689)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setWindowOpacity(2.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_welcome = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_welcome.sizePolicy().hasHeightForWidth())
        self.label_welcome.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(19, 92, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 92, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_welcome.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_welcome.setFont(font)
        self.label_welcome.setObjectName("label_welcome")
        self.horizontalLayout_4.addWidget(self.label_welcome)
        spacerItem = QtWidgets.QSpacerItem(149, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tum_logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tum_logo.sizePolicy().hasHeightForWidth())
        self.tum_logo.setSizePolicy(sizePolicy)
        self.tum_logo.setMinimumSize(QtCore.QSize(150, 60))
        self.tum_logo.setMaximumSize(QtCore.QSize(150, 60))
        self.tum_logo.setText("")
        self.tum_logo.setPixmap(QtGui.QPixmap("logo_tum.png"))
        self.tum_logo.setScaledContents(True)
        self.tum_logo.setObjectName("tum_logo")
        self.horizontalLayout_7.addWidget(self.tum_logo)
        self.wfp_logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wfp_logo.sizePolicy().hasHeightForWidth())
        self.wfp_logo.setSizePolicy(sizePolicy)
        self.wfp_logo.setMinimumSize(QtCore.QSize(90, 90))
        self.wfp_logo.setMaximumSize(QtCore.QSize(90, 90))
        self.wfp_logo.setText("")
        self.wfp_logo.setPixmap(QtGui.QPixmap("logo_wfp.png"))
        self.wfp_logo.setScaledContents(True)
        self.wfp_logo.setObjectName("wfp_logo")
        self.horizontalLayout_7.addWidget(self.wfp_logo)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, 10, 10, 30)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.text_top = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_top.setFont(font)
        self.text_top.setObjectName("text_top")
        self.horizontalLayout_6.addWidget(self.text_top)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_selectfiles = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_selectfiles.setFont(font)
        self.groupBox_selectfiles.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_selectfiles.setAutoFillBackground(False)
        self.groupBox_selectfiles.setStyleSheet("")
        self.groupBox_selectfiles.setFlat(False)
        self.groupBox_selectfiles.setObjectName("groupBox_selectfiles")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_selectfiles)
        self.gridLayout_2.setContentsMargins(-1, -1, 9, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_main = QtWidgets.QLineEdit(self.groupBox_selectfiles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_main.sizePolicy().hasHeightForWidth())
        self.lineEdit_main.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_main.setFont(font)
        self.lineEdit_main.setObjectName("lineEdit_main")
        self.gridLayout.addWidget(self.lineEdit_main, 0, 1, 1, 1)
        self.label_choose_main = QtWidgets.QLabel(self.groupBox_selectfiles)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_main.setFont(font)
        self.label_choose_main.setTextFormat(QtCore.Qt.AutoText)
        self.label_choose_main.setObjectName("label_choose_main")
        self.gridLayout.addWidget(self.label_choose_main, 0, 0, 1, 1)
        self.browseButton_main = QtWidgets.QPushButton(self.groupBox_selectfiles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton_main.sizePolicy().hasHeightForWidth())
        self.browseButton_main.setSizePolicy(sizePolicy)
        self.browseButton_main.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.browseButton_main.setFont(font)
        self.browseButton_main.setObjectName("browseButton_main")
        self.gridLayout.addWidget(self.browseButton_main, 0, 2, 1, 1)
        self.gridLayout.setColumnMinimumWidth(2, 100)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_selectfiles)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_details = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_details.sizePolicy().hasHeightForWidth())
        self.groupBox_details.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_details.setFont(font)
        self.groupBox_details.setObjectName("groupBox_details")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_details)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spinBox_vehicles = QtWidgets.QSpinBox(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_vehicles.sizePolicy().hasHeightForWidth())
        self.spinBox_vehicles.setSizePolicy(sizePolicy)
        self.spinBox_vehicles.setMinimumSize(QtCore.QSize(65, 21))
        self.spinBox_vehicles.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.spinBox_vehicles.setBaseSize(QtCore.QSize(65, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_vehicles.setFont(font)
        self.spinBox_vehicles.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_vehicles.setAccelerated(True)
        self.spinBox_vehicles.setMinimum(1)
        self.spinBox_vehicles.setMaximum(999)
        self.spinBox_vehicles.setObjectName("spinBox_vehicles")
        self.gridLayout_3.addWidget(self.spinBox_vehicles, 0, 4, 1, 1)
        self.spinBox_Q1 = QtWidgets.QSpinBox(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Q1.sizePolicy().hasHeightForWidth())
        self.spinBox_Q1.setSizePolicy(sizePolicy)
        self.spinBox_Q1.setMinimumSize(QtCore.QSize(65, 21))
        self.spinBox_Q1.setMaximumSize(QtCore.QSize(10000, 65))
        self.spinBox_Q1.setBaseSize(QtCore.QSize(65, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_Q1.setFont(font)
        self.spinBox_Q1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_Q1.setAccelerated(True)
        self.spinBox_Q1.setMinimum(1)
        self.spinBox_Q1.setProperty("value", 10)
        self.spinBox_Q1.setObjectName("spinBox_Q1")
        self.gridLayout_3.addWidget(self.spinBox_Q1, 1, 4, 1, 1)
        self.label_choose_Q2 = QtWidgets.QLabel(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_choose_Q2.sizePolicy().hasHeightForWidth())
        self.label_choose_Q2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_Q2.setFont(font)
        self.label_choose_Q2.setObjectName("label_choose_Q2")
        self.gridLayout_3.addWidget(self.label_choose_Q2, 2, 3, 1, 1)
        self.doubleSpinBox_loadingtime = QtWidgets.QDoubleSpinBox(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_loadingtime.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_loadingtime.setSizePolicy(sizePolicy)
        self.doubleSpinBox_loadingtime.setMinimumSize(QtCore.QSize(65, 21))
        self.doubleSpinBox_loadingtime.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.doubleSpinBox_loadingtime.setBaseSize(QtCore.QSize(65, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_loadingtime.setFont(font)
        self.doubleSpinBox_loadingtime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_loadingtime.setAccelerated(True)
        self.doubleSpinBox_loadingtime.setMaximum(10.0)
        self.doubleSpinBox_loadingtime.setProperty("value", 0.5)
        self.doubleSpinBox_loadingtime.setObjectName("doubleSpinBox_loadingtime")
        self.gridLayout_3.addWidget(self.doubleSpinBox_loadingtime, 1, 1, 1, 1)
        self.label_choose_time = QtWidgets.QLabel(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_choose_time.sizePolicy().hasHeightForWidth())
        self.label_choose_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_time.setFont(font)
        self.label_choose_time.setObjectName("label_choose_time")
        self.gridLayout_3.addWidget(self.label_choose_time, 0, 0, 1, 1)
        self.spinBox_Q2 = QtWidgets.QSpinBox(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Q2.sizePolicy().hasHeightForWidth())
        self.spinBox_Q2.setSizePolicy(sizePolicy)
        self.spinBox_Q2.setMinimumSize(QtCore.QSize(65, 21))
        self.spinBox_Q2.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.spinBox_Q2.setBaseSize(QtCore.QSize(65, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_Q2.setFont(font)
        self.spinBox_Q2.setWrapping(False)
        self.spinBox_Q2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_Q2.setAccelerated(True)
        self.spinBox_Q2.setMinimum(1)
        self.spinBox_Q2.setProperty("value", 20)
        self.spinBox_Q2.setObjectName("spinBox_Q2")
        self.gridLayout_3.addWidget(self.spinBox_Q2, 2, 4, 1, 1)
        self.label_choose_avgspeed = QtWidgets.QLabel(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_choose_avgspeed.sizePolicy().hasHeightForWidth())
        self.label_choose_avgspeed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_avgspeed.setFont(font)
        self.label_choose_avgspeed.setObjectName("label_choose_avgspeed")
        self.gridLayout_3.addWidget(self.label_choose_avgspeed, 3, 0, 1, 1)
        self.doubleSpinBox_maxtime = QtWidgets.QDoubleSpinBox(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_maxtime.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_maxtime.setSizePolicy(sizePolicy)
        self.doubleSpinBox_maxtime.setMinimumSize(QtCore.QSize(65, 21))
        self.doubleSpinBox_maxtime.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.doubleSpinBox_maxtime.setBaseSize(QtCore.QSize(65, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_maxtime.setFont(font)
        self.doubleSpinBox_maxtime.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.doubleSpinBox_maxtime.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.doubleSpinBox_maxtime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_maxtime.setAccelerated(True)
        self.doubleSpinBox_maxtime.setMaximum(10.0)
        self.doubleSpinBox_maxtime.setProperty("value", 5.0)
        self.doubleSpinBox_maxtime.setObjectName("doubleSpinBox_maxtime")
        self.gridLayout_3.addWidget(self.doubleSpinBox_maxtime, 2, 1, 1, 1)
        self.label_choose_maxtime = QtWidgets.QLabel(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_choose_maxtime.sizePolicy().hasHeightForWidth())
        self.label_choose_maxtime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_maxtime.setFont(font)
        self.label_choose_maxtime.setObjectName("label_choose_maxtime")
        self.gridLayout_3.addWidget(self.label_choose_maxtime, 2, 0, 1, 1)
        self.label_choose_vehicles = QtWidgets.QLabel(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_choose_vehicles.sizePolicy().hasHeightForWidth())
        self.label_choose_vehicles.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_vehicles.setFont(font)
        self.label_choose_vehicles.setObjectName("label_choose_vehicles")
        self.gridLayout_3.addWidget(self.label_choose_vehicles, 0, 3, 1, 1)
        self.doubleSpinBox_cw1 = QtWidgets.QDoubleSpinBox(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_cw1.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_cw1.setSizePolicy(sizePolicy)
        self.doubleSpinBox_cw1.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinBox_cw1.setBaseSize(QtCore.QSize(65, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_cw1.setFont(font)
        self.doubleSpinBox_cw1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_cw1.setAccelerated(True)
        self.doubleSpinBox_cw1.setDecimals(4)
        self.doubleSpinBox_cw1.setMinimum(-100.0)
        self.doubleSpinBox_cw1.setMaximum(100.0)
        self.doubleSpinBox_cw1.setObjectName("doubleSpinBox_cw1")
        self.gridLayout_3.addWidget(self.doubleSpinBox_cw1, 3, 4, 1, 1)
        self.spinBox_TimeHorizon = QtWidgets.QSpinBox(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_TimeHorizon.sizePolicy().hasHeightForWidth())
        self.spinBox_TimeHorizon.setSizePolicy(sizePolicy)
        self.spinBox_TimeHorizon.setMinimumSize(QtCore.QSize(65, 21))
        self.spinBox_TimeHorizon.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.spinBox_TimeHorizon.setBaseSize(QtCore.QSize(65, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_TimeHorizon.setFont(font)
        self.spinBox_TimeHorizon.setWrapping(False)
        self.spinBox_TimeHorizon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_TimeHorizon.setAccelerated(True)
        self.spinBox_TimeHorizon.setMinimum(1)
        self.spinBox_TimeHorizon.setMaximum(12)
        self.spinBox_TimeHorizon.setObjectName("spinBox_TimeHorizon")
        self.gridLayout_3.addWidget(self.spinBox_TimeHorizon, 0, 1, 1, 1)
        self.label_choose_loadingtime = QtWidgets.QLabel(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_choose_loadingtime.sizePolicy().hasHeightForWidth())
        self.label_choose_loadingtime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_loadingtime.setFont(font)
        self.label_choose_loadingtime.setObjectName("label_choose_loadingtime")
        self.gridLayout_3.addWidget(self.label_choose_loadingtime, 1, 0, 1, 1)
        self.doubleSpinBox_avgspeed = QtWidgets.QDoubleSpinBox(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_avgspeed.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_avgspeed.setSizePolicy(sizePolicy)
        self.doubleSpinBox_avgspeed.setMinimumSize(QtCore.QSize(60, 21))
        self.doubleSpinBox_avgspeed.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.doubleSpinBox_avgspeed.setBaseSize(QtCore.QSize(65, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_avgspeed.setFont(font)
        self.doubleSpinBox_avgspeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_avgspeed.setAccelerated(True)
        self.doubleSpinBox_avgspeed.setMaximum(200.0)
        self.doubleSpinBox_avgspeed.setProperty("value", 50.0)
        self.doubleSpinBox_avgspeed.setObjectName("doubleSpinBox_avgspeed")
        self.gridLayout_3.addWidget(self.doubleSpinBox_avgspeed, 3, 1, 1, 1)
        self.label_choose_costspkm = QtWidgets.QLabel(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_choose_costspkm.sizePolicy().hasHeightForWidth())
        self.label_choose_costspkm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_costspkm.setFont(font)
        self.label_choose_costspkm.setObjectName("label_choose_costspkm")
        self.gridLayout_3.addWidget(self.label_choose_costspkm, 4, 0, 1, 1)
        self.doubleSpinBox_costsperkm = QtWidgets.QDoubleSpinBox(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_costsperkm.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_costsperkm.setSizePolicy(sizePolicy)
        self.doubleSpinBox_costsperkm.setMinimumSize(QtCore.QSize(65, 21))
        self.doubleSpinBox_costsperkm.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.doubleSpinBox_costsperkm.setBaseSize(QtCore.QSize(65, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_costsperkm.setFont(font)
        self.doubleSpinBox_costsperkm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_costsperkm.setAccelerated(True)
        self.doubleSpinBox_costsperkm.setProperty("value", 0.1)
        self.doubleSpinBox_costsperkm.setObjectName("doubleSpinBox_costsperkm")
        self.gridLayout_3.addWidget(self.doubleSpinBox_costsperkm, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_details)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStatusTip("")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 3, 1, 1)
        self.doubleSpinBox_cw2 = QtWidgets.QDoubleSpinBox(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_cw2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_cw2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_cw2.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinBox_cw2.setBaseSize(QtCore.QSize(65, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_cw2.setFont(font)
        self.doubleSpinBox_cw2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_cw2.setAccelerated(True)
        self.doubleSpinBox_cw2.setDecimals(4)
        self.doubleSpinBox_cw2.setMinimum(-100.0)
        self.doubleSpinBox_cw2.setMaximum(100.0)
        self.doubleSpinBox_cw2.setProperty("value", 0.0)
        self.doubleSpinBox_cw2.setObjectName("doubleSpinBox_cw2")
        self.gridLayout_3.addWidget(self.doubleSpinBox_cw2, 3, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.label_choose_Q1 = QtWidgets.QLabel(self.groupBox_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_choose_Q1.sizePolicy().hasHeightForWidth())
        self.label_choose_Q1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_choose_Q1.setFont(font)
        self.label_choose_Q1.setObjectName("label_choose_Q1")
        self.gridLayout_3.addWidget(self.label_choose_Q1, 1, 3, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_details)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 4, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_details)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        self.pushButton_close.setMinimumSize(QtCore.QSize(170, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_5.addWidget(self.pushButton_close, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 1)
        self.pushButton_opt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_opt.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_opt.sizePolicy().hasHeightForWidth())
        self.pushButton_opt.setSizePolicy(sizePolicy)
        self.pushButton_opt.setMinimumSize(QtCore.QSize(170, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_opt.setFont(font)
        self.pushButton_opt.setCheckable(False)
        self.pushButton_opt.setObjectName("pushButton_opt")
        self.gridLayout_5.addWidget(self.pushButton_opt, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 22))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDecision_Tool_Help = QtWidgets.QAction(MainWindow)
        self.actionDecision_Tool_Help.setObjectName("actionDecision_Tool_Help")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Cliparts/clipart schließen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.menuHelp.addAction(self.actionDecision_Tool_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label_choose_main.setBuddy(self.lineEdit_main)
        self.label_choose_Q2.setBuddy(self.spinBox_Q2)
        self.label_choose_time.setBuddy(self.spinBox_TimeHorizon)
        self.label_choose_avgspeed.setBuddy(self.doubleSpinBox_avgspeed)
        self.label_choose_maxtime.setBuddy(self.doubleSpinBox_maxtime)
        self.label_choose_vehicles.setBuddy(self.spinBox_vehicles)
        self.label_choose_loadingtime.setBuddy(self.doubleSpinBox_loadingtime)
        self.label_choose_costspkm.setBuddy(self.doubleSpinBox_costsperkm)
        self.label.setBuddy(self.doubleSpinBox_cw1)
        self.label_choose_Q1.setBuddy(self.spinBox_Q1)

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.pushButton_close.pressed.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_main, self.browseButton_main)
        MainWindow.setTabOrder(self.browseButton_main, self.spinBox_TimeHorizon)
        MainWindow.setTabOrder(self.spinBox_TimeHorizon, self.doubleSpinBox_loadingtime)
        MainWindow.setTabOrder(self.doubleSpinBox_loadingtime, self.doubleSpinBox_maxtime)
        MainWindow.setTabOrder(self.doubleSpinBox_maxtime, self.doubleSpinBox_avgspeed)
        MainWindow.setTabOrder(self.doubleSpinBox_avgspeed, self.doubleSpinBox_costsperkm)
        MainWindow.setTabOrder(self.doubleSpinBox_costsperkm, self.spinBox_vehicles)
        MainWindow.setTabOrder(self.spinBox_vehicles, self.spinBox_Q1)
        MainWindow.setTabOrder(self.spinBox_Q1, self.spinBox_Q2)
        MainWindow.setTabOrder(self.spinBox_Q2, self.pushButton_opt)
        MainWindow.setTabOrder(self.pushButton_opt, self.pushButton_close)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Decision Tool WFP@TUM"))
        self.label_welcome.setText(_translate("MainWindow", "Welcome to the Optimization Decision Tool!"))
        self.text_top.setText(_translate("MainWindow", "Select the appropriate files below, define your time horizon and click on \'Optimize\' to get your optimal route.  It will also\n"
"give you all information about the assignments as an output."))
        self.groupBox_selectfiles.setTitle(_translate("MainWindow", "Select files"))
        self.label_choose_main.setText(_translate("MainWindow", "Choose main file:"))
        self.browseButton_main.setStatusTip(_translate("MainWindow", "Select the file with all data for warehouses and schools."))
        self.browseButton_main.setText(_translate("MainWindow", "Browse"))
        self.groupBox_details.setTitle(_translate("MainWindow", "More details"))
        self.spinBox_vehicles.setStatusTip(_translate("MainWindow", "Choose the number of vehicles per warehouse that deliver to schools."))
        self.spinBox_Q1.setStatusTip(_translate("MainWindow", "Choose the capacity for the vehicles that deliver to schools."))
        self.label_choose_Q2.setText(_translate("MainWindow", "Capacity of vehicles to central warehouses:"))
        self.doubleSpinBox_loadingtime.setStatusTip(_translate("MainWindow", "Choose the time (in hours) that it takes to (un)load the food."))
        self.label_choose_time.setText(_translate("MainWindow", "Time Horizon:"))
        self.spinBox_Q2.setStatusTip(_translate("MainWindow", "Choose the capacity for the vehicles that pick up from the central warehouse."))
        self.label_choose_avgspeed.setText(_translate("MainWindow", "Average speed:"))
        self.doubleSpinBox_maxtime.setStatusTip(_translate("MainWindow", "Choose the maximal number of hours for a trip."))
        self.label_choose_maxtime.setText(_translate("MainWindow", "Max. time for a trip:"))
        self.label_choose_vehicles.setText(_translate("MainWindow", "Number of vehicles:"))
        self.doubleSpinBox_cw1.setStatusTip(_translate("MainWindow", "Type in the coordinates (between -100 and 100) for the central warehouse."))
        self.spinBox_TimeHorizon.setStatusTip(_translate("MainWindow", "Choose the number of weeks over which it will optimize."))
        self.label_choose_loadingtime.setText(_translate("MainWindow", "Loading time:"))
        self.doubleSpinBox_avgspeed.setStatusTip(_translate("MainWindow", "Choose the average speed for the vehicles."))
        self.label_choose_costspkm.setText(_translate("MainWindow", "Costs per km:"))
        self.doubleSpinBox_costsperkm.setStatusTip(_translate("MainWindow", "Choose the costs per kilometer."))
        self.label.setText(_translate("MainWindow", "Central warehouse:"))
        self.doubleSpinBox_cw2.setStatusTip(_translate("MainWindow", "Type in the coordinates (between -100 and 100) for the central warehouse."))
        self.label_choose_Q1.setText(_translate("MainWindow", "Capacity of vehicles to schools:"))
        self.checkBox.setText(_translate("MainWindow", "Use mean central instead"))
        self.pushButton_close.setStatusTip(_translate("MainWindow", "Click here to exit the decision tool."))
        self.pushButton_close.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_close.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_opt.setStatusTip(_translate("MainWindow", "Click here to start the optimization."))
        self.pushButton_opt.setText(_translate("MainWindow", "Optimize"))
        self.pushButton_opt.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About the developers"))
        self.actionDecision_Tool_Help.setText(_translate("MainWindow", "Decision Tool - Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
